namespace AndroidEntryMaxLengthBug
{
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
            LongTextEntry.Text = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget nunc egestas, pulvinar tellus ut, aliquam lacus. Nam ac elit non felis mattis facilisis sed non felis. Nam ut posuere arcu. In tincidunt vitae velit non pulvinar. Vivamus nisi neque, interdum ac nibh eget, fringilla fringilla nisi. Quisque quis enim mattis, fermentum quam eleifend, congue mi. Curabitur lorem enim, dictum sit amet dolor vel, tincidunt ornare arcu. Nullam eu enim ex. Cras eu consectetur nisl, vel efficitur nisi. Donec in metus ultricies, lacinia sapien ac, tempus turpis. Sed magna neque, ultricies eget eleifend et, ullamcorper eu felis. Quisque erat tortor, auctor ornare ultrices id, molestie nec tellus.

Cras cursus metus lorem, ac accumsan purus dignissim pellentesque. Proin placerat ipsum sed commodo molestie. In suscipit velit id leo vulputate placerat. Nulla a erat rutrum, vestibulum diam et, lobortis leo. Praesent venenatis non tortor eu rhoncus. Duis blandit iaculis tortor nec maximus. Morbi congue enim eu odio vulputate, sit amet facilisis eros finibus. Vivamus vitae leo molestie, consectetur sem ut, viverra felis.

Nulla in volutpat justo. Nunc varius molestie quam ac rutrum. Nulla sagittis nec elit scelerisque dictum. In convallis libero tempor elementum scelerisque. Fusce sit amet lacus congue, porta dui et, imperdiet ligula. Morbi quam odio, sodales volutpat aliquam id, aliquet eget orci. In euismod vulputate vestibulum. Nulla orci dui, fermentum ac augue et, facilisis convallis magna. Pellentesque maximus tincidunt ligula quis vestibulum. Phasellus imperdiet tortor eget turpis rhoncus, eget lacinia erat dignissim. Ut aliquet turpis libero. Pellentesque rutrum magna a ipsum rhoncus sodales. Nulla placerat augue turpis, in euismod nunc semper nec.

Nulla vitae ipsum eu quam eleifend aliquam ut sed ipsum. Donec leo velit, fermentum at pretium rhoncus, euismod quis turpis. Integer sed libero fringilla, pellentesque risus nec, mollis nisi. Suspendisse feugiat arcu quis dui commodo, et congue lacus ornare. Nulla varius malesuada augue quis lobortis. Ut nec congue sapien, sed sollicitudin urna. Vivamus mollis egestas enim non molestie. Aenean a felis ac nibh luctus aliquam at sed ipsum. Aenean ac sagittis sem. Aliquam tempor in neque in feugiat. Vivamus elementum interdum eros, sit amet hendrerit odio vestibulum non. Curabitur scelerisque, quam ut semper vulputate, ante nibh mattis ligula, eu convallis purus tellus eget nibh.

Phasellus efficitur pretium ante, et viverra est vulputate in. Etiam laoreet at enim viverra accumsan. Nullam semper posuere pharetra. Suspendisse ullamcorper, elit et lacinia lacinia, odio dui euismod nunc, a venenatis dolor nulla in justo. Duis convallis dui mi, id varius erat finibus in. Phasellus ultrices est ut sem aliquam ultrices. Morbi mollis tellus sem, eu venenatis tellus pretium at.

Pellentesque laoreet purus non purus ultrices lacinia. Phasellus vitae accumsan nisi. Fusce pretium, orci eget rutrum tempor, elit neque pretium sapien, nec tempor neque risus eget urna. Fusce bibendum lectus sit amet gravida pretium. Phasellus vitae orci quis tortor dapibus ullamcorper id sed ipsum. Quisque elit turpis, placerat nec tempus nec, tincidunt sed nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sem tellus, suscipit a ex et, auctor condimentum est. In arcu eros, varius et condimentum id, consequat quis odio. Praesent varius leo in lectus sollicitudin, vitae volutpat nulla ullamcorper. Curabitur facilisis, lorem ut faucibus semper, eros erat mollis libero, id varius nibh tortor quis est. Vivamus convallis hendrerit nulla, vel vehicula ipsum placerat ut. Integer et magna sed enim interdum tempor et eget lorem. Aliquam molestie faucibus nisi.

Nunc justo est, sollicitudin quis erat in, accumsan gravida neque. Aenean dapibus ipsum non leo volutpat, sed tempor odio volutpat. Ut tristique velit eu orci sagittis facilisis. Aliquam et nunc eget erat dignissim convallis ac at massa. Nulla pulvinar ultricies leo, eu tincidunt augue ullamcorper tempor. Fusce sit amet est vel urna ultrices consequat. Vestibulum luctus suscipit gravida. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam ac dapibus erat. Cras non tincidunt sapien. Vivamus pulvinar ligula elit, eget dapibus est malesuada eget. Fusce eget gravida diam. Morbi sed dolor laoreet tellus feugiat gravida. Proin in diam venenatis, cursus leo sit amet, tristique leo.

Sed cursus orci eget tempus molestie. Vivamus rutrum eros nisl, in venenatis nibh semper id. Nam vitae lectus a risus rhoncus condimentum. Sed nec elit sapien. Sed tristique urna eget ex lobortis consequat. Quisque ut enim elementum, hendrerit nisi a, porta libero. Etiam facilisis mauris nec orci consequat faucibus. Aliquam elit arcu, laoreet et fermentum quis, rhoncus vitae erat. Etiam eleifend consectetur sollicitudin.

Aenean finibus laoreet nisl, sed egestas dui euismod sit amet. Cras mollis turpis a ante commodo imperdiet. In mi mauris, scelerisque vitae imperdiet ut, pellentesque ut mauris. Fusce gravida enim non purus faucibus, sed blandit nisi tempus. Nunc ac tincidunt justo. Curabitur in nulla non leo pretium ornare. Donec vitae lectus ipsum. Nulla urna lectus, laoreet vitae egestas volutpat, fringilla lacinia nisl. Nulla quis tincidunt nunc. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam dapibus turpis orci, pretium dictum metus auctor vel. In a ultricies arcu. Mauris sapien tellus, viverra sed lobortis facilisis, hendrerit sit amet lorem. Mauris dictum diam a erat semper, id pharetra nunc vulputate. Ut vitae scelerisque nisi.

Nunc facilisis accumsan convallis. Quisque sed dui sed leo rutrum dictum sit amet eget sem. Nunc nisl arcu, tincidunt at tortor id, rutrum aliquet urna. Sed non pharetra nulla, ut suscipit nisl. Fusce molestie fermentum nisl, ac eleifend turpis egestas at. Vestibulum semper dui vitae ultrices tincidunt. Etiam vestibulum orci aliquam.";
        }
    }
}
